#!/bin/sh -e

# Check parameters

if [ "$1" = "" ] && [ "$2" = "" ] && [ "$3" = "" ]
then
    echo "Usage:"
    echo "$0 components infrastructure distribution"
    exit 1;
fi

# Get absolute paths of models

components=`readlink -f $1`
infrastructure=`readlink -f $2`
distribution=`readlink -f $3`
exportexpr=`readlink -f ./export.nix`

# Generate expression which generates a distribution model

echo "Generate distribution nix expression..." >&2

tmpfilename=`mktemp -p /tmp`
echo "Filename is: $tmpfilename" >&2

cat > $tmpfilename <<EOF
rec {
    pkgs = import (builtins.getEnv "NIXPKGS_ALL") { };
EOF
( echo "    infrastructure = import $infrastructure;"
  echo "    components = import $components;"
  echo "    distribution = import $distribution {"
) >> $tmpfilename
cat >> $tmpfilename <<EOF
	inherit components infrastructure;
    };
EOF
echo "    export = import $exportexpr {" >> $tmpfilename
cat >> $tmpfilename <<EOF
	inherit distribution;
	inherit (pkgs) stdenv;
    };
}
EOF

# Create XML export of distribution

echo "Instantiate the expression..." >&2
drvPaths="`nix-instantiate $tmpfilename`"
echo "derivations: $drvPaths" >&2

echo "Realising the expression..." >&2
outPath="`nix-store --realise $drvPaths`"
echo "$outPath"

# Remove temp files

rm -f $tmpfilename
