#!/bin/sh -e

if [ "$DISNIX_SOAP_HOME" = "" ]
then
    PRG="`which $0`"
    REALPRG="`readlink -f $PRG`"
    DISNIX_SOAP_HOME="`dirname $REALPRG`"
fi

# Axis2 libraries

AXIS2_PATH=/home/sander/axis2-1.4
AXIS2_LIB=""

for i in $AXIS2_PATH/lib/*.jar
do
    AXIS2_LIB="$AXIS2_LIB:$i"
done

# Execute client

java -cp $DISNIX_SOAP_HOME/jargs.jar:$AXIS2_LIB:$DISNIX_SOAP_HOME/DisnixClient.jar org.nixos.disnix.client.DisnixCollectGarbage $@
