#!/bin/bash -e

# Resolve the path of the Disnix soap utilities

if [ "$DISNIX_SOAP_HOME" = "" ]
then
    PRG="`type -p $0`"
    REALPRG="`readlink -f $PRG`"
    DISNIX_SOAP_HOME="`dirname $REALPRG`"
fi

# Add Axis2 libraries to the classpath

if [ "$AXIS2_LIBDIR" = "" ]
then
    AXIS2_LIBDIR=
fi

AXIS2_LIB=""

for i in $AXIS2_LIBDIR/*.jar
do
    AXIS2_LIB="$AXIS2_LIB:$i"
done

# Execute client

java -Xms32m -Xmx256m -cp $DISNIX_SOAP_HOME/jargs.jar:$AXIS2_LIB:$DISNIX_SOAP_HOME/DisnixClient.jar org.nixos.disnix.client.DisnixDeploy $@
